Repository TAMAS-Inc/tama, pull requests merged in 2022-12, with the labels that each got.

#50 Create pull_request_template.md
  .github/pull_request_template.md
Labels: 문서

#66 [Feat] inquiry 페이지 Modal 기능 개발
  src/@types/user.d.ts
  src/components/Modal/Modal.tsx
  src/components/index.ts
  src/pages/Menu/Inquiry/index.tsx
Labels: 기능개발

#80 [Feature] 버스 분석 페이지로 이동 및 렌더링
  src/pages/Main/Analysis/Analysis.stories.tsx
  src/pages/Main/Analysis/index.tsx
  src/pages/Main/hooks/useQueryString.ts
  src/pages/Main/index.tsx
  src/utils/date.ts
Labels: 리팩토링

#81 [Feature] 출근지 추가, 삭제, 편집
  src/components/MessageModal/MessageModal.stories.tsx
  src/components/MessageModal/MessageModal.tsx
  src/components/MessageModal/index.ts
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/index.ts
  src/components/index.ts
  src/hooks/useCommutes.ts
  src/pages/Main/components/CommuteModal/CommuteModal.tsx
  src/pages/Main/hooks/useAnalysis.ts
  src/pages/Menu/Inquiry/index.tsx
  src/pages/commute/components/ConfirmModal/ConfirmModal.stories.tsx
  src/pages/commute/components/ConfirmModal/ConfirmModal.tsx
  src/pages/commute/components/ConfirmModal/index.ts
  src/pages/commute/components/index.ts
  src/pages/commute/edit/index.tsx
Labels: 기능개발

#82 feat: Add Search logic
  package.json
  src/pages/commute/hooks/useAvailableRoutes.ts
  src/pages/commute/searchStation/[id].tsx
Labels: 기능개발

#88 Feature/#55
  .eslintrc.json
  src/components/Notification/Notification.tsx
  src/pages/Main/hooks/useNotice.ts
  src/pages/Menu/Notice/[id].tsx
  src/pages/Menu/Notice/index.tsx
  src/utils/notice.ts
Labels: 기능개발

#95 [Feature] Add atom Editing State
  src/@types/user.d.ts
  src/hooks/useCommutes.ts
  src/pages/Landing/agreement/index.tsx
  src/pages/Main/components/CommuteModal/CommuteModal.tsx
  src/pages/commute/edit/[id].tsx
  src/pages/commute/edit/index.tsx
  src/pages/commute/hooks/useAvailableRoutes.ts
  src/pages/commute/searchStation/[id].tsx
  src/routes/index.tsx
  src/state/atom.tsx
Labels: 리팩토링

#122 [Feat] UI/UX 개선 및 BaseModal 애니메이션 적용
  package.json
  src/components/BaseModal/BaseModal.tsx
  src/components/Header/Header.tsx
  src/components/NavigationHeader/NavigationHeader.tsx
  src/constants/style.ts
  src/pages/Landing/agreement/index.tsx
  src/pages/Main/components/CommuteModal/CommuteModal.tsx
  src/pages/Main/components/MainHeader/MainHeader.tsx
  src/pages/Main/components/MainMenu/MainMenu.tsx
  src/pages/commute/edit/[id].tsx
  src/pages/commute/searchStation/[id].tsx
Labels: 스타일

#123 [Feat] sync 버튼 Auto Fetching 구현, LoadingWithDelay 컴포넌트 생성
  package-lock.json
  src/components/LoadingWithDelay/LoadingWithDelay.tsx
  src/components/LoadingWithDelay/index.ts
  src/components/SyncButton/SyncButton.tsx
  src/components/index.ts
  src/pages/Main/index.tsx
  src/pages/Menu/Notice/[id].tsx
  src/pages/Menu/Notice/index.tsx
  src/pages/commute/edit/[id].tsx
  src/pages/commute/searchStation/[id].tsx
Labels: 기능개발

#124 bug: Add focus logic on ResetButton
  src/pages/commute/edit/[id].tsx
  src/pages/commute/searchStation/[id].tsx
  vite.config.ts
Labels: 버그

#127 Feature/#118
  src/index.css
Labels: 버그

#128 hotfix: Merge by yiju, jiseung
  package-lock.json
  src/assets/data/openSourceData/OFL.txt
  src/assets/data/openSourceData/index.ts
  src/assets/data/termsOfServices/index.ts
  src/assets/favicons/android-chrome-144x144.png
  src/assets/favicons/apple-touch-icon.png
  src/assets/favicons/browserconfig.xml
  src/assets/favicons/favicon-16x16.png
  src/assets/favicons/favicon-32x32.png
  src/assets/favicons/favicon.ico
  src/assets/favicons/mstile-150x150.png
  src/assets/favicons/pwa-192x192.png
  src/assets/favicons/pwa-512x512.png
  src/assets/favicons/safari-pinned-tab.svg
  src/assets/favicons/site.webmanifest
  src/assets/fonts/LINE_Seed_Sans_KR/Webfont/WOFF2/LINESeedKR-Bd.woff2
  src/assets/fonts/LINE_Seed_Sans_KR/Webfont/WOFF2/LINESeedKR-Rg.woff2
  src/assets/logo/full_logo.svg
  src/assets/logo/logo.svg
  src/components/Error/Error.tsx
  src/components/SyncButton/SyncButton.tsx
  src/index.css
  src/pages/Main/Analysis/index.tsx
  src/pages/Main/RouteMap/[id].tsx
  src/pages/Main/index.tsx
  src/pages/Menu/OpenSource/[id].tsx
  src/pages/Menu/OpenSource/index.tsx
  src/pages/Menu/Terms/index.tsx
  vite.config.ts
Labels: 버그

#135 [Feat] Sync 버튼 자동 데이터 fetching 로직 수정 및 SyncButtonWithoutTime 컴포넌트 추가
  src/components/SyncButton/SyncButton.tsx
  src/components/SyncButtonWithoutTime/SyncButtonWithoutTime.stories.tsx
  src/components/SyncButtonWithoutTime/SyncButtonWithoutTime.tsx
  src/components/SyncButtonWithoutTime/index.ts
  src/components/index.ts
  src/pages/Main/Analysis/index.tsx
  src/pages/Main/index.tsx
  src/pages/commute/edit/[id].tsx
Labels: 기능개발, 스타일
